update script

diff --git a/bin/chuid b/bin/chuid
--- a/bin/chuid
+++ b/bin/chuid
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -e
 
 USERNAME=$1
 NEWUID=$2
@@ -10,6 +11,12 @@ usage() {
 
 if [ "$#" -lt 2 ]; then
     usage
+    exit 1
+fi
+
+# check that running as root
+if [ $UID -ne 0 ]; then
+    echo "Error: please run as root."
     exit 1
 fi
 
@@ -45,7 +52,7 @@ GROUP=$(getent group $OLDGID | awk -F: '{print $1}')
 echo "Changing from $USERNAME to have uid:gid -> $NEWUID:$NEWGID."
 echo "   press Ctrl-C to abort, press enter to continue..."
 read
-sudo usermod -u $NEWUID -g $NEWGID $USERNAME
-sudo groupmod -g $NEWGID $GROUP
-sudo find /  -user $OLDUID -exec chown .$NEWUID \{\} \
-sudo find / -group $OLDGID -exec chown .$NEWGID {} \;
+groupmod -g $NEWGID $GROUP
+usermod -u $NEWUID -g $NEWGID $USERNAME
+find /  -user $OLDUID -exec chown $NEWUID {} \;
+find / -group $OLDGID -exec chown .$NEWGID {} \;
